language: cpp

compiler:
    - gcc
    - clang

before_install:
    - ./admin/travis-install-deps.sh

env:
    - AS_ROOT=no
    - AS_ROOT=yes UNPRIVILEGED_USER=no
    - AS_ROOT=yes UNPRIVILEGED_USER=yes

script:
    - ./admin/travis-build.sh

notifications:
    email:
        - kyua-log@googlegroups.com
